### PR TITLE
`super-linter`: Add configuration for `textlinter`

### PR DESCRIPTION
**Pull request by razvand**
Add `.textlintrc` configuration file for textlinter. It allows certain common words that `textlinter` (the terminology plugin) would complain about.

### CODE REVIEW

**Review by gabrielmocanu — CHANGES_REQUESTED** [review]
This won't work with `superlinter` since as you can see [here] the `mv` command won't copy `.textlintrc` command. You need to change the `mv` command to move all files hidden and unhidden or add another mv command special for `.textlintrc`.

[here]: https://github.com/security-summer-school/actions/blob/4d29cbb4887260c32de3fd8cd9621a686daa5593/super-linter/action.yml#L25-L29

**Comment by razvand** [comment]
> This won't work with `superlinter` since as you can see [here](https://github.com/security-summer-school/actions/blob/4d29cbb4887260c32de3fd8cd9621a686daa5593/super-linter/action.yml#L25-L29) the `mv` command won't copy `.textlintrc` command. You need to change the `mv` command to move all files hidden and unhidden or add another mv command special for `.textlintrc`.

OK. Makes sense. But why is that rule there to begin with? Why not use the default path for the linter configs?

**Comment by razvand** [comment]
> This won't work with `superlinter` since as you can see [here](https://github.com/security-summer-school/actions/blob/4d29cbb4887260c32de3fd8cd9621a686daa5593/super-linter/action.yml#L25-L29) the `mv` command won't copy `.textlintrc` command. You need to change the `mv` command to move all files hidden and unhidden or add another mv command special for `.textlintrc`.

Fixed.

**Review by gabrielmocanu — APPROVED** [review]

**Comment by gabrielmocanu** [comment]
@razvand  
I don't think I get your question but those config files are not present by default in the runner because this action starts with a checkout step that will clone only the repository content in which the action runs.
So for example, if this action runs in the OS repository, we need a way to move the general config files from this repository to the runner.
We can use the default path, but those `mv` commands are still mandatory to be done to the default path of the linter(whatever that is).
I chose to use a custom path because in this way it was more obvious why those config files should be put there and you have a always a reminder( contributor / reviewer ) that you should add an `mv` command for your configuration files.

**Comment by razvand** [comment]
>  I chose to use a custom path because in this way it was more obvious why those config files should be put there and you have always a reminder( contributor / reviewer ) that you should add an mv command for your configuration files.

But why chose the `.linter-config/` directory and not just use the `config-action/actions-main/super-linter/` directory?

**Pull request merged**
